import React from 'react';

interface PrivacyPolicyProps {
  onClose: () => void;
}

const PrivacyPolicy: React.FC<PrivacyPolicyProps> = ({ onClose }) => {
  return (
    <div 
      className="fixed inset-0 bg-black/60 flex items-center justify-center z-50 animate-fade-in"
      onClick={onClose}
      role="dialog"
      aria-modal="true"
      aria-labelledby="privacy-policy-title"
    >
      <div 
        className="bg-[var(--color-bg-secondary)] p-6 md:p-8 rounded-xl shadow-2xl max-w-2xl w-[90%] max-h-[85vh] overflow-y-auto relative"
        onClick={e => e.stopPropagation()} // Prevent clicks inside from closing the modal
      >
        <button 
          onClick={onClose}
          className="absolute top-4 right-4 text-[var(--color-text-secondary)] hover:text-[var(--color-accent-primary)] transition-colors"
          aria-label="Close privacy policy"
        >
          <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
            <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>

        <h2 id="privacy-policy-title" className="text-2xl md:text-3xl font-bold text-[var(--color-text-primary)] mb-6">Privacy Policy</h2>
        
        <p className="text-[var(--color-text-secondary)] mb-4">Last updated: {new Date().toLocaleDateString()}</p>
        
        <p className="text-[var(--color-text-secondary)] mb-6">
          Your privacy is critically important to us. This Typing Speed Test application is designed with privacy as a fundamental principle.
        </p>

        <h3 className="text-xl font-semibold text-[var(--color-text-primary)] mt-6 mb-3">1. Data Collection and Storage</h3>
        <p className="text-[var(--color-text-secondary)] mb-4">
          <strong>We do not collect, transmit, or store any of your personal data on our servers.</strong> All data generated by your use of this application is stored locally on your device within your web browser's storage (`localStorage`).
        </p>
        <p className="text-[var(--color-text-secondary)] mb-4">
          This locally stored data includes:
        </p>
        <ul className="list-disc list-inside text-[var(--color-text-secondary)] space-y-2 mb-4">
          <li><strong>Typing Test History:</strong> Your WPM scores, accuracy percentages, chosen difficulty, and timestamps for each test you complete.</li>
          <li><strong>User Preferences:</strong> Your preferred theme, test duration, and difficulty level.</li>
        </ul>
        <p className="text-[var(--color-text-secondary)] mb-4">
          This data remains under your control, on your device. Clearing your browser's cache or site data for this application will permanently delete all your history and preferences.
        </p>

        <h3 className="text-xl font-semibold text-[var(--color-text-primary)] mt-6 mb-3">2. Data Usage</h3>
        <p className="text-[var(--color-text-secondary)] mb-4">
          The data stored locally is used solely to enhance your experience with the application. Specifically, it allows us to:
        </p>
        <ul className="list-disc list-inside text-[var(--color-text-secondary)] space-y-2 mb-4">
          <li>Display your progress and historical performance in the chart on the main page.</li>
          <li>Remember your preferred settings (theme, difficulty, time) for your convenience.</li>
          <li>Provide a personalized and consistent experience across sessions.</li>
        </ul>

        <h3 className="text-xl font-semibold text-[var(--color-text-primary)] mt-6 mb-3">3. No Third-Party Sharing</h3>
        <p className="text-[var(--color-text-secondary)] mb-4">
          Since we do not collect your data, we do not and cannot share it with any third parties. There are no third-party analytics, advertisers, or tracking scripts on this application.
        </p>
        
        <h3 className="text-xl font-semibold text-[var(--color-text-primary)] mt-6 mb-3">4. Cookies</h3>
        <p className="text-[var(--color-text-secondary)] mb-4">
          This website does not use traditional cookies for tracking. We use `localStorage`, a standard web technology, which is essential for the application's core functionality as described above. It is not used to track you across other websites.
        </p>

        <h3 className="text-xl font-semibold text-[var(--color-text-primary)] mt-6 mb-3">5. Changes to This Privacy Policy</h3>
        <p className="text-[var(--color-text-secondary)] mb-4">
          We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page. You are advised to review this Privacy Policy periodically for any changes.
        </p>

        <div className="mt-8 text-center">
            <button 
                onClick={onClose}
                className="px-8 py-3 bg-[var(--color-accent-secondary)] text-[var(--color-text-inverted)] font-bold text-lg rounded-md hover:bg-[var(--color-accent-primary)] transition-all transform hover:scale-105 focus:outline-none focus:ring-4 focus:ring-[var(--color-accent-primary)]"
            >
                Close
            </button>
        </div>
      </div>
    </div>
  );
};

export default PrivacyPolicy;